### ISSUE TITLE
Different Aspect ratios for all the users

### ISSUE THREAD

**Issue by midopooler** [mexili/incogly#100]
Different Aspect ratios of the video for all the users

**Comment by sansyrox** [comment]
<img width="1317" alt="Screenshot 2021-06-29 at 1 00 07 AM" src="https://user-images.githubusercontent.com/29942790/123693302-80e1ff80-d875-11eb-8ed7-c097d26085d8.png">

This is the sandbox fix that I have thought of. Will implement it over the weekend.

**Comment by sansyrox** [comment]
This is fixed!
