### ISSUE TITLE
Landing page gif broken

### ISSUE THREAD

**Issue by midopooler** [mexili/incogly#101]
The GIF file on the Landing page is broken and is showing a blur image. Need a quick fix.

**Comment by ZohebMOPO** [comment]
@sansyrox, @midopooler  Which one should we go for?
![demo1](https://user-images.githubusercontent.com/72716462/123901795-49fd0e00-d989-11eb-9d9a-5c8940313920.JPG)
![demo 2](https://user-images.githubusercontent.com/72716462/123901802-4ec1c200-d989-11eb-81a5-6c36088b75ac.JPG)

**Comment by ZohebMOPO** [comment]
P.S. These gifs are in motion but while taking a screenshot it is static.

**Comment by sansyrox** [comment]
@ZohebMOPO , you can put these gifs in the comments for us to view. Also, can you try looking for gifs that are maybe more colorful? They don't have to be related to code and can just be related to collaboration.

**Comment by ZohebMOPO** [comment]
Alr,
[1](https://www.careerguide.com/career/wp-content/uploads/2020/04/collaboration-clipart-animated-gif-2.gif)
[2](https://cdn.dribbble.com/users/4341791/screenshots/8574595/media/3cbca4ba607b111c4d4702f210062a62.gif)
[3](https://static.wixstatic.com/media/570bfa_55217a8ab97d4cf1a206fe2ca2f5e2cf~mv2.gif) <- This one is my favorite.

**Comment by sansyrox** [comment]
@ZohebMOPO , all of these look good. If you can change the background to transparent ,then you can make a PR with any gif that you like 😄

**Comment by midopooler** [comment]
Ummm. Third one looks more like a dating website GIF lol

**Comment by ZohebMOPO** [comment]
Haha.
What about [this](https://static.wixstatic.com/media/ab8e83_ed69dcb2b5b341e99ddfc77323599475~mv2.gif) and [this](https://cdn.dribbble.com/users/37380/screenshots/10883216/zoom-party4_12fps.gif) one.

**Comment by sansyrox** [comment]
https://cdn.dribbble.com/users/37380/screenshots/10883216/zoom-party4_12fps.gif this one looks nice

**Comment by sansyrox** [comment]
You can also have a look at these : https://cdn.dribbble.com/users/37380/screenshots/10883216/zoom-party4_12fps.gif

**Comment by ZohebMOPO** [comment]
Sure

**Comment by ZohebMOPO** [comment]
But the problem is it's occupying too much space on the home page

**Comment by sansyrox** [comment]
What do you mean?

**Comment by ZohebMOPO** [comment]
nvm, that was a problem with `<iframe>` tag. It's fixed. I am making a PR then.

**Comment by sansyrox** [comment]
Fixed here: https://github.com/mexili/incogly/pull/105
