### ISSUE TITLE
Cloudflare not working for some reason!

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#106]
main website not working!!

Netlify working. Don't know why.

**Comment by ZohebMOPO** [comment]
Is it a problem because of my PR? cuz I saw out of 5 tests 3 passed and 2 were neutral. This may not be the problem ig.

**Comment by sansyrox** [comment]
@ZohebMOPO , nope. It is def something else. Maybe with webpack or dns.

**Comment by sansyrox** [comment]
Fixed. Website is up now!
