### ISSUE TITLE
Port Application to Typescript

### ISSUE THREAD

**Issue by shivaylamba** [mexili/incogly#118]
@sansyrox Raghav is suggesting to port all components to Typescript. 

Refer : https://github.com/raghavdhingra/React-Typescript-Webpack-Scss-boilerplate ( Sample Template CRA for TypeScript )

**Comment by sansyrox** [comment]
Not permitted.
Types are dumb.

**Comment by sansyrox** [comment]
Types are dumb!
Not permitted.

**Comment by sansyrox** [comment]
https://twitter.com/sansyrox/status/1376229000469618689

Tenet.
