### ISSUE TITLE
Bump up react

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#13]
Migrate to a newer version

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @sansyrox

**Comment by sansyrox** [comment]
Sure @subhangi2731 . Go ahead

**Comment by sansyrox** [comment]
We plan to assign only one issue at a time 😄

**Comment by subhangi2731** [comment]
okay no problem..will fix the first issue then come to next

**Comment by sansyrox** [comment]
Fixed.
