### ISSUE TITLE
App doesn't work in cross platform and crashes when using my laptop

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#14]
Issue is unique to my laptop and with other people

Need to check if this is with my network or just the laptop

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @sansyrox

**Comment by sansyrox** [comment]
How do you plan to debug this?

This issue is unique to me.

**Comment by mohdorusaid** [comment]
Can you describe some details and error messages?

**Comment by sansyrox** [comment]
@mohdorusaid , that is the strange thing. It doesn't give any errors just doesn't connect to a session.

This bug is unique to me. I would have to fix it myself :(. I would suggest y'all work on a different bug maybe #6 is good alternative to this one.

**Comment by mohdorusaid** [comment]
Sure I'll look around:)

**Comment by sansyrox** [comment]
Fixed Now.
Wierd Issue with the Nginx proxy settings.
