### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by atarax665** [mexili/incogly#17]
### Add ```CONTRIBUTING.md``` File

As this project is a part of an Open Source Program ```NJACK Winter of Code``` I would recommend to have a contribution guidelines file (```CONTRIBUTING.md```) to assist beginners to get started with open source contribution.

Points to be covered in the guideline :
- How to pull your first request.
- How to create issue.
- Some general rules to keep in mind while contributing to an open source project.
- Links of some tutorials which will help beginners to learn the basics of git and github.

**Comment by Pranav016** [comment]
Sure, I would be happy to add a CONTRIBUTING file.

**Comment by sansyrox** [comment]
Sure! Go ahead @Pranav016

**Comment by atarax665** [comment]
@sansyrox @Pranav016 Actually I was already working on this issue. I have even raised PR #20 regarding it.

**Comment by sansyrox** [comment]
Økay @atarax665 . From next time please claim the issue before working to avoid any botch ups.

**Comment by atarax665** [comment]
> Økay @atarax665 . From next time please claim the issue before working to avoid any botch ups.

Yeah, sorry for the inconvenience.
