### ISSUE TITLE
Add the option of adding more than one member

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#19]
Currently, the video call happens only between 2 people. 

We need to add a way to allow more than 2.

**Comment by Jassi10000-zz** [comment]
Heyy @sansyrox , I want to try this out 
Btw I have currently requested to work on issue #69 , after that I want to work on this , so am requesting to assign it to me beforehand , so that this doesn't get crowded
Btw pls add the tags as well

**Comment by sansyrox** [comment]
Hey @Jassi10000 , this feature is already implemented in the PR, I proposed here https://github.com/mexili/incogly/pull/67

This PR has some issues that require some help. You can try contributing to those. And as soon as that PR gets merged, we will have more issues like this one.

**Comment by Jassi10000-zz** [comment]
> Hey @Jassi10000 , this feature is already implemented in the PR, I proposed here #67
> 
> This PR has some issues that require some help. You can try contributing to those. And as soon as that PR gets merged, we will have more issues like this one.

Means am late , anyways , can you pls tell what are the issues that require help , I can try to help the team to make it a better project

**Comment by sansyrox** [comment]
We support multiple people now. Closing this!
