### ISSUE TITLE
Improve the 404 page!

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#25]
404 is a little ugly rn.

We can add a simple svg from undraw to improve the aesthetics!

**Comment by sayna3311** [comment]
I would like to contribute. Please, assign this to me.

**Comment by sansyrox** [comment]
Yes, sure @sayna3311 . Go ahead!

**Comment by sayna3311** [comment]
![Screenshot 2020-12-07 223304](https://user-images.githubusercontent.com/67572440/101381018-3cdcdc80-38dc-11eb-8467-4c0b1ef38ed4.jpg)

Looks fine to you?

**Comment by sansyrox** [comment]
@sayna3311 This looks really good! 🔥
