### ISSUE TITLE
Create a Landing Page

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#28]
Right now the Landing Page is a little old and the fonts are not very crisp on different screens.

You can create a new landing page as per your imagination.

Requirements:
1. Get the mockup approved
2. Make the PR.

We can split the PR into 2 issues and can allot the points as required.

**Comment by akshay1027** [comment]
@sansyrox can i work on this issue sir?

**Comment by sansyrox** [comment]
@akshay1027 , we have already created the dark mode one. Will be interested in creating the light mode version?

**Comment by sansyrox** [comment]
![](https://cdn.discordapp.com/attachments/780403248360062990/786881607624818708/Screenshot_2020-12-11_at_2.36.30_PM.png)


Here is a dark mode design. Lmk if you can propose a light mode one.

**Comment by akshay1027** [comment]
ohh, that's cool, i will try to propose the light mode then 🙌🏻! @sansyrox

**Comment by akshay1027** [comment]
I have made a pull request for the lightmode version. review it and let me know what else i have to change. Also i have not changed the navbar for lightmode, if you give me permission, i would like to to that as well. @sansyrox

**Comment by sansyrox** [comment]
@akshay1027 , please go ahead!

**Comment by lopeselio** [comment]
Is the issue still open ?

**Comment by sansyrox** [comment]
Hi @lopeselio ,

Yes, it is still open!

**Comment by sansyrox** [comment]
We have to implement the design in the comment: https://github.com/mexili/incogly/issues/28#issuecomment-745115912

using scss and chakraui preferably, but you are free to choose whatever you like.

**Comment by sansyrox** [comment]
If you just want to propose a design, we require a light version of the darkmode proposed above.

**Comment by RutvikJ77** [comment]
> If you just want to propose a design, we require a light version of the darkmode proposed above.

I am in for that

**Comment by RutvikJ77** [comment]
Hey @sansyrox, I developed this light version can you check it. It is just UI design.
![Incogly - light](https://user-images.githubusercontent.com/45565999/108593058-68c61500-7397-11eb-83d4-dfc629f1b032.png)

**Comment by sansyrox** [comment]
@RutvikJ77 , this looks great! Do you want to help with coding it out as well?

**Comment by RutvikJ77** [comment]
> @RutvikJ77 , this looks great! Do you want to help with coding it out as well?

If it is in react, it will take some time for me to set it up since it will be a new tech stack additionally I will need to develop through scss right?

**Comment by sansyrox** [comment]
@RutvikJ77 , yes. Take a look at this: https://chakra-ui.com/getting-started

It makes using react much simpler for creating is.

Also, can you share the design files in a PR, so I can allot you your points.

**Comment by RutvikJ77** [comment]
Cool! I did go through Chakra UI seems easy to develop. I will give it my try. Okay! I will share the background image and UI for the homepage.

**Comment by sansyrox** [comment]
We have a good landing page now. Closing this!
