### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by m-code12** [mexili/incogly#42]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor.

Demo :
<img src="https://user-images.githubusercontent.com/1641039/78471193-71573200-776a-11ea-9b40-810c2d63270e.png">

**Comment by m-code12** [comment]
@sansyrox Should I implement this?

**Comment by sansyrox** [comment]
Yes @m-code12 , go ahead! 🔥
