### ISSUE TITLE
Add a github logo on the landing page to navigate user to the github repo

### ISSUE THREAD

**Issue by lopeselio** [mexili/incogly#69]
**Is your feature request related to a problem? Please describe.**
The user would want to view the code repository and having a footer icon in the anding page would navigate the user to the codebase

**Additional context**
No additional context

**Comment by Jassi10000-zz** [comment]
If this means that click the logo would direct it to the github repo of Incogly , then I want to definitely try this out , assign me this
Also pls mention the tags as well

**Comment by sansyrox** [comment]
@lopeselio @Jassi10000 , you can add this issue on this PR https://github.com/mexili/incogly/pull/67 and the major_refactor branch.

**Comment by NishantJawla** [comment]
@sansyrox  can I work on this issue. This would be my first opensource commit and it looks like a great issue for a begineer

**Comment by lopeselio** [comment]
Okay, are we supposed to create a new landing page for the project and before making other changes.

**Comment by vikas-099** [comment]
@sansyrox Can I work on this issue ? I am a total beginner. Thanks

**Comment by sansyrox** [comment]
@trishnakalita660 @lopeselio @vikas-099 , this issue is not an active issue at the moment. Please try to solve the issues on this PR #67 https://github.com/mexili/incogly/pull/67

**Comment by lopeselio** [comment]
Okay cool

**Comment by vikas-099** [comment]
Okay no problem
