### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Jassi10000-zz** [mexili/incogly#70]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
1. In the steps to get started with the Installation , the 3. step is written wrong in the ReadMe , due to which many of my beginner friends are facing  issues  -----> Its written  " yarn && node server.js" 
2. In the steps it's my suggestion to please include this point that any  contributor first has to install node modules or typically express , but yeah something related to installation should be written 

### These 2 are the problems faced by some beginners who are willing to contribute but getting confused

**Describe the solution you'd like**
1. I want to correct the 3. step to   " yarn   or  node server.js  "
2. I want to include in the readme to install the necessary package or module which is needed to run the following command "node server.js" or "yarn server.js"

**Describe alternatives you've considered**
No, the correct steps I mentioned will help everyone to go smooth 

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Comment by lopeselio** [comment]
Hey but yarn installs all packages and node server.js is used to run the server behind the application. Which I guess is not a problem.

**Comment by Jassi10000-zz** [comment]
@lopeselio Acc to my knowledge , you can either use yarn or (npm) [the package manager of node ]

Both can't be used together
Btw with  " node " also we can install all packages

**Comment by Jassi10000-zz** [comment]
@sansyrox Can you pls have a look over my issue raised , it's it seems suitable pls assign me so that I can move forward to correct the docs

**Comment by sansyrox** [comment]
Yarn is a package manager.

Node is a RTE.

@Jassi10000 , you can read more about them here: https://stackoverflow.com/questions/41675848/what-is-the-difference-between-node-js-runtime-and-npm-package-manager-options-w/41676076#:~:text=js%20runtime%20is%20basically%20what,by%20using%20the%20command%20line.

**Comment by Jassi10000-zz** [comment]
> Yarn is a package manager.
> 
> Node is a RTE.
> 
> @Jassi10000 , you can read more about them here: https://stackoverflow.com/questions/41675848/what-is-the-difference-between-node-js-runtime-and-npm-package-manager-options-w/41676076#:~:text=js%20runtime%20is%20basically%20what,by%20using%20the%20command%20line.

Npm , is also the package manager of Node , its a choice to use yarn or npm

**Comment by sansyrox** [comment]
![Screenshot 2021-02-17 at 5 50 07 PM](https://user-images.githubusercontent.com/29942790/108203491-95d0b880-7148-11eb-8043-d40b41200940.png)

> Npm , is also the package manager of Node , its a choice to use yarn or npm

Yes @Jassi10000 , I am aware of that. Thought of clarifying your issue 😄

**Comment by Jassi10000-zz** [comment]
> ![Screenshot 2021-02-17 at 5 50 07 PM](https://user-images.githubusercontent.com/29942790/108203491-95d0b880-7148-11eb-8043-d40b41200940.png)
> 
> > Npm , is also the package manager of Node , its a choice to use yarn or npm
> 
> Yes @Jassi10000 , I am aware of that. Thought of clarifying your issue 😄

No issues sir ,😄🤙
