### ISSUE TITLE
Check why the the app is making us log out on chat send?

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#91]
**Describe the bug**
The app is ending the call when the user sends the chat in the socket stream.

**To Reproduce**
1.  Join the call
2.  Try to send the message
3.  App will log you out

**Expected behavior**
The app should successfully send the app to the backend

**Actual behavior**
Crashing at the moment

**Comment by ZohebMOPO** [comment]
![bug](https://user-images.githubusercontent.com/72716462/121991094-99a1de00-cdbc-11eb-9576-c1350341aed3.JPG)

I am trying to send messages it's not logging me out. The messages are not showing up in the chat cause there is no Database. But it is not logging me out. I guess the problem was that time.

**Comment by sansyrox** [comment]
@ZohebMOPO , you need to have 2 people in the socket room.

**Comment by ZohebMOPO** [comment]
![No bug](https://user-images.githubusercontent.com/72716462/122021006-e7314180-cde2-11eb-94e8-1f0f587ccc0e.JPG)
No, it is not @sansyrox and there is a problem that the next person is not showing after he/she joins. I figured it out. The problem that if your webcam is used in one place then it couldn't be used in another place. If we host that in the cloud and another person joins with another device, it will show I guess.

**Comment by sansyrox** [comment]
@ZohebMOPO 
> I figured it out. The problem that if your webcam is used in one place then it couldn't be used in another place.

This is not the case. This was working well locally before the refactor. You can join from two tabs without incognito mode and this should work well.(in an ideal scenario)

Read my comments here: https://github.com/mexili/incogly/issues/92#issuecomment-860943842

I have a feeling that these two might be connected.

**Comment by ZohebMOPO** [comment]
I literally changed the browser and did that so that there will be no conflicts. Idk then what's happening.
P.S. I checked the thing in my normal browser first it was working fine and then I did that in incognito and screenshotted that so that I can hide my normal chrome unnecessary tabs.

**Comment by sansyrox** [comment]
Fixed in the latest release. GG 🔥
