### ISSUE TITLE
Video stream not showing when a second person is being added to the call

### ISSUE THREAD

**Issue by sansyrox** [mexili/incogly#92]
**Describe the bug**

**To Reproduce**
1.  Open video call
2.  Make some else join it
3.  Video stream will not be visible

**Expected behavior**
Both video streams should be visible

**Comment by sansyrox** [comment]
@raghavdhingra , I think I might know core cause of this issue.

`getMedia` and `connectToSocketServer` function are being called based on `useEffect`s . We just want them to be called on the basis of button click and not just the change of the state `askForUsername`.

What we should do instead of  this 

```jsx
	useEffect(() => {
		if (!state.askForUsername) {
			getMedia();
		}
		// eslint-disable-next-line
	}, [state.askForUsername]);
```

we should use this:

```jsx
	const connect = () => {
            setState({ ...state, askForUsername: false })
            getMedia();
            };
```

**Comment by sansyrox** [comment]
and as you will go up the function stack, I think you will move closer to the solution.

**Comment by raghavdhingra** [comment]
<img width="1440" alt="Screenshot 2021-06-20 at 4 11 42 PM" src="https://user-images.githubusercontent.com/24492201/122670994-3e1f8800-d1e2-11eb-8de0-c91845ff232f.png">

Added a timeout, for obtaining the user stream. But working on a single end.
I will try to update the video based on the socket connection

**Comment by raghavdhingra** [comment]
@sansyrox I think we have to revert Zoheb changes

**Comment by sansyrox** [comment]
This is fixed in the latest release! gg 🔥
