### ISSUE TITLE
Enter keystroke not mapped with the inputfields. 

### ISSUE THREAD

**Issue by midopooler** [mexili/incogly#97]
Enter keystroke not mapped with the input fields.

**Comment by ZohebMOPO** [comment]
@sansyrox I didn't get what the issue is tryna say. Do we need some keyboard shortcuts so that it will work with input fields?. I was reading [this](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap) to understand but I can't :(

**Comment by sansyrox** [comment]
@Zoheb, when you type anything in the input box, you need to click on
submit button to submit.
We need to make the enter button do this as well.

**Comment by ZohebMOPO** [comment]
Ahh alright

**Comment by ZohebMOPO** [comment]
![Error](https://user-images.githubusercontent.com/72716462/124691750-f5621180-def9-11eb-96c7-bb3f6d006ad7.JPG)
Idk why I am facing this error. After surfing google a lot I found out that this a `Babel` version problem. What should I do then? @sansyrox

**Comment by ZohebMOPO** [comment]
![errr](https://user-images.githubusercontent.com/72716462/124692771-ce0c4400-defb-11eb-94b3-430f6194bfd7.JPG)
not even this one

**Comment by ZohebMOPO** [comment]
[Code](https://github.com/ZohebMOPO/incogly/blob/temp/src/components/Home/index.jsx)

**Comment by sansyrox** [comment]
```
<Input
								className="home_page__input_box"
								placeholder="Enter unique ID or link"
								value={roomId}
								onChange={handleChange}
								onKeyDown={handleKeyPress}
							/>
							<Button
								className="home_page__join_button"
								variant="contained"
								onClick={joinRoom}
								ref={handleKeyPress}
								type="submit"
							>
```


`handleKeyPress` is being duplicated. You are using it as a ref as well as a callback, which is wrong.


```
	const handleKeyPress = (e) => {
		if (e.key === 'Enter') {
			this.btn.click();
		}
	};

```

We don't use `this` in functional components

**Comment by ZohebMOPO** [comment]
Ahh, alright I fixed that thing and it's working now. @sansyrox 
[Demo](https://youtu.be/wQ7O-ReauKA). Making a PR

**Comment by sansyrox** [comment]
Completed
